// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_kill_everyone = "CgkI8NWqp_kREAIQBw"; // <GPGSID>
        public const string achievement_get_1_powerup = "CgkI8NWqp_kREAIQBA"; // <GPGSID>
        public const string achievement_get_3_powerups = "CgkI8NWqp_kREAIQCQ"; // <GPGSID>
        public const string achievement_get_all_powerups = "CgkI8NWqp_kREAIQBQ"; // <GPGSID>
        public const string achievement_kill_3_enemies = "CgkI8NWqp_kREAIQCA"; // <GPGSID>
        public const string achievement_end_the_game_in_3_minutes = "CgkI8NWqp_kREAIQCg"; // <GPGSID>
        public const string achievement_get_all_knifes = "CgkI8NWqp_kREAIQAw"; // <GPGSID>
        public const string achievement_kill_1_enemy = "CgkI8NWqp_kREAIQBg"; // <GPGSID>
        public const string achievement_end_the_game_with_5_lifes = "CgkI8NWqp_kREAIQCw"; // <GPGSID>
        public const string achievement_get_1_knife = "CgkI8NWqp_kREAIQAg"; // <GPGSID>
        public const string achievement_end_the_game = "CgkI8NWqp_kREAIQAQ"; // <GPGSID>

}

